# Generated by Django 4.1.6 on 2023-06-18 08:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deekshaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254)),
                ('courseTitle', models.CharField(max_length=200)),
                ('obtainedScore', models.IntegerField()),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='Questiontext',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
