# Generated by Django 4.1.6 on 2023-06-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deekshaapp', '0002_assessmentresults_alter_question_questiontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresults',
            name='percentageObtained',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='assessmentresults',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
