# Generated by Django 4.1.6 on 2023-06-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deekshaapp', '0003_assessmentresults_percentageobtained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresults',
            name='percentageObtained',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
