# Generated by Django 4.1.6 on 2023-06-28 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deekshaapp', '0004_alter_assessmentresults_percentageobtained'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('alternateNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(max_length=500)),
                ('schoolName', models.CharField(max_length=500)),
                ('xpercentage', models.IntegerField()),
                ('xcourse', models.TextField(max_length=500)),
                ('xdate', models.CharField(max_length=100)),
                ('xcity', models.CharField(max_length=100)),
                ('collegeName', models.CharField(max_length=300)),
                ('xiipercentage', models.IntegerField()),
                ('xiicourse', models.TextField(max_length=500)),
                ('xiidate', models.CharField(max_length=100)),
                ('xiicity', models.CharField(max_length=100)),
                ('universityName', models.TextField(max_length=300)),
                ('universitypercentage', models.IntegerField()),
                ('branch', models.CharField(max_length=200)),
                ('startdate', models.CharField(max_length=100)),
                ('enddate', models.CharField(max_length=100)),
                ('universitycity', models.CharField(blank=True, max_length=100, null=True)),
                ('muniversityName', models.TextField(blank=True, max_length=300, null=True)),
                ('muniversitypercentage', models.IntegerField(blank=True, null=True)),
                ('mbranch', models.CharField(blank=True, max_length=200, null=True)),
                ('mstartdate', models.CharField(blank=True, max_length=100, null=True)),
                ('menddate', models.CharField(blank=True, max_length=100, null=True)),
                ('muniversitycity', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.TextField(max_length=500)),
                ('p1', models.CharField(blank=True, max_length=100, null=True)),
                ('p1d', models.TextField(blank=True, max_length=500, null=True)),
                ('p2', models.CharField(blank=True, max_length=100, null=True)),
                ('p2d', models.TextField(blank=True, max_length=500, null=True)),
                ('i1', models.CharField(blank=True, max_length=100, null=True)),
                ('i1d', models.TextField(blank=True, max_length=500, null=True)),
                ('i2', models.CharField(blank=True, max_length=100, null=True)),
                ('i2d', models.TextField(blank=True, max_length=500, null=True)),
                ('github', models.TextField(blank=True, max_length=500, null=True)),
                ('linkedin', models.TextField(blank=True, max_length=500, null=True)),
                ('facebook', models.TextField(blank=True, max_length=500, null=True)),
                ('instagram', models.TextField(blank=True, max_length=500, null=True)),
                ('role', models.CharField(blank=True, max_length=150, null=True)),
                ('summary', models.TextField(blank=True, max_length=500, null=True)),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
