# Generated by Django 4.1.6 on 2023-07-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deekshaapp', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='muniversitypercentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
