# Generated by Django 4.1.6 on 2023-07-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deekshaapp', '0006_alter_profile_muniversitypercentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('intershipcertificate1', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('internshipcertificate2', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('course1Name', models.CharField(blank=True, max_length=150, null=True)),
                ('course1Score', models.IntegerField(blank=True, null=True)),
                ('course1certificate', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('course2Name', models.CharField(blank=True, max_length=150, null=True)),
                ('course2Score', models.IntegerField(blank=True, null=True)),
                ('course2certificate', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('course3Name', models.CharField(blank=True, max_length=150, null=True)),
                ('course3Score', models.IntegerField(blank=True, null=True)),
                ('course3certificate', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('course4Name', models.CharField(blank=True, max_length=150, null=True)),
                ('course4Score', models.IntegerField(blank=True, null=True)),
                ('course4certificate', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='p1l',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='p2l',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
