# Generated by Django 4.1.6 on 2023-07-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deekshaapp', '0007_certifications_profile_p1l_profile_p2l_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='img',
        ),
    ]
