# Generated by Django 4.1.6 on 2023-07-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deekshaapp', '0008_remove_assessment_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresults',
            name='improvementPlans',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(default='which topic this question comes from', max_length=500),
        ),
    ]
