# Generated by Django 4.1.6 on 2023-07-08 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deekshaapp', '0009_assessmentresults_improvementplans_question_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorSupportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('taskName', models.CharField(max_length=100)),
                ('taskDescription', models.TextField(max_length=500)),
                ('taskCompleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taskAssignedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
