# Generated by Django 4.1.6 on 2023-07-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deekshaapp', '0010_advisorsupporttask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifications',
            name='course1Name',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='course1Score',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='course1certificate',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='course2Name',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='course2Score',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='course2certificate',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='course3Name',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='course3Score',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='course3certificate',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='course4Name',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='course4Score',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='course4certificate',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='internshipcertificate2',
        ),
        migrations.RemoveField(
            model_name='certifications',
            name='intershipcertificate1',
        ),
        migrations.AddField(
            model_name='certifications',
            name='courseCertificate',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='certifications',
            name='courseName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='certifications',
            name='courseScore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
