# Generated by Django 4.1.6 on 2023-07-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deekshaapp', '0011_remove_certifications_course1name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifications',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certifications',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
