# Generated by Django 4.1.6 on 2023-07-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deekshaapp', '0012_certifications_name_alter_certifications_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='courseScore',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
